language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'

addons:
    code_climate:
        repo_token: d2944566aa6c29a653033381d197274f95a709ee3206cab7bf57900b0b2427b8

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
